import { globSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// Claims check: the prose is a claim, and this is the gate that reads it.
//
// Every other check in this repo inspects code. `catalog:check` proves
// catalog.json matches schemas.ts; `gallery:check` proves every registered
// Block has an example; `brand:check` proves no source file names the brand.
// None of them can see a sentence, and the sentences are what an authoring
// agent reads first.
//
// That gap was not theoretical. v0 added two Blocks in live sessions
// (`Comparison` on #51, `PostGrid` on #34). Both landed correctly: schema,
// component, registry, catalog, gallery example, every gate green. And after
// them the README still said the registry "ships 14 Blocks", and
// compose-page — the skill an agent loads before composing anything — still
// listed 14 names, missing both. An agent reading that list would not know
// the Block it needed already existed, and would either work around its
// absence or add a duplicate.
//
// So the numbers and the list are duplicated on purpose (an agent skimming the
// skill should not have to open catalog.json to pick a Block), and this check
// is the price of the duplication.
//
// Exported as pure functions over strings, like scripts/pr-hygiene.ts, so
// every rule is unit-testable without touching the filesystem.

export interface Claim {
  /** Repo-relative path of the file making the claim. */
  file: string;
  /** 1-indexed line the claim is on. */
  line: number;
  /** What is wrong, addressed to whoever has to fix it. */
  message: string;
}

/** The Block registry, as the generated catalog reports it. */
export interface Registry {
  count: number;
  names: string[];
}

export const registryFrom = (catalogJson: string): Registry => {
  const parsed = JSON.parse(catalogJson) as { blockCount: number; blocks: Record<string, unknown> };
  return { count: parsed.blockCount, names: Object.keys(parsed.blocks) };
};

/** Line number (1-indexed) of a character offset within a source string. */
const lineAt = (source: string, index: number): number => source.slice(0, index).split("\n").length;

/**
 * Rule 1 — a spelled-out count: "ships **14 Blocks**", "Today's 14 Blocks".
 *
 * Only a digit immediately followed by the word "Block(s)" counts. Prose that
 * spells a number out ("a page of fifteen unrelated Blocks", design-a-block)
 * is deliberately not matched: it reads as an illustration rather than a
 * claim, and gating it would push authors into writing digits everywhere.
 */
export const checkCount = (file: string, source: string, registry: Registry): Claim[] => {
  const claims: Claim[] = [];
  for (const match of source.matchAll(/(\d+)\s+Blocks?\b/g)) {
    const claimed = Number(match[1]);
    if (claimed === registry.count) continue;
    claims.push({
      file,
      line: lineAt(source, match.index),
      message:
        `claims ${claimed} Blocks; the registry has ${registry.count}.\n` +
        `    Source of truth: artifacts/web/src/lib/blocks/catalog.json (regenerated by \`pnpm catalog\`).`,
    });
  }
  return claims;
};

/**
 * Rule 2 — a `"blockCount": N` sample. compose-page shows catalog.json's shape
 * with a real value, which is more useful to a reader than an elided one and
 * goes stale exactly as easily as the prose around it.
 */
export const checkSample = (file: string, source: string, registry: Registry): Claim[] => {
  const claims: Claim[] = [];
  for (const match of source.matchAll(/"blockCount":\s*(\d+)/g)) {
    const claimed = Number(match[1]);
    if (claimed === registry.count) continue;
    claims.push({
      file,
      line: lineAt(source, match.index),
      message: `shows \`"blockCount": ${claimed}\` in a catalog.json sample; the real value is ${registry.count}.`,
    });
  }
  return claims;
};

const TRIGGER = "Blocks: `";

/**
 * Rule 3 — an inline enumeration of every Block by name.
 *
 * Deliberately narrow. It fires only on the literal phrasing ``Blocks: ` ``,
 * which introduces a complete list, and reads to the end of that sentence.
 * Ordinary prose naming two or three Blocks as examples ("such as `Hero`,
 * `FeatureGrid`, `Testimonial`, and `CTA`", README) never trips it, because a
 * list of examples is not introduced that way.
 *
 * The sentence ends at the first "." followed by whitespace or end-of-input.
 * A Block name cannot contain a full stop, so no name is ever cut in half.
 */
export const checkEnumeration = (file: string, source: string, registry: Registry): Claim[] => {
  const claims: Claim[] = [];
  let from = 0;
  while (true) {
    const start = source.indexOf(TRIGGER, from);
    if (start === -1) break;
    from = start + TRIGGER.length;

    const rest = source.slice(start);
    const end = rest.search(/\.(\s|$)/);
    const sentence = end === -1 ? rest : rest.slice(0, end);

    const listed = [...sentence.matchAll(/`([A-Z][A-Za-z0-9]*)`/g)].map((m) => m[1]);
    const missing = registry.names.filter((name) => !listed.includes(name));
    const unknown = listed.filter((name) => !registry.names.includes(name));
    if (missing.length === 0 && unknown.length === 0) continue;

    claims.push({
      file,
      line: lineAt(source, start),
      message:
        `enumerates the Block registry and does not match it.\n` +
        (missing.length > 0 ? `    Missing: ${missing.join(", ")}\n` : "") +
        (unknown.length > 0 ? `    Not in the registry: ${unknown.join(", ")}\n` : "") +
        `    List every name in artifacts/web/src/lib/blocks/catalog.json, or reword so the ` +
        `sentence does not read as a complete list.`,
    });
  }
  return claims;
};

/**
 * Rule 4 — a Stats cell counting the registry.
 *
 * The three rules above read prose, and content MDX does not make its claim in
 * prose. It makes it as data: `{ value: "14", label: "Blocks in the registry
 * today" }`, where the figure and the noun are separated by a quote, a comma
 * and a key, so rule 1's digit-then-Block pattern never sees them. That gap
 * let the same claim drift three different ways at once -- 14 on the home
 * page, 12 in the gallery, 14 again in a blog post -- against a registry of
 * 16, with every gate green.
 *
 * Deliberately narrow: it keys off the literal label rather than trying to
 * read MDX generally, because a Block prop is data and the only claim in it
 * that has ever gone stale is this one. A general prose checker over content
 * is a different and much larger thing.
 */
export const checkStatCell = (file: string, source: string, registry: Registry): Claim[] => {
  const claims: Claim[] = [];
  // `value` then `label`, the order the Block's own schema declares them in.
  const pattern = /value:\s*"(\d+)"[^}]*?label:\s*"Blocks in the registry/g;
  for (const match of source.matchAll(pattern)) {
    const claimed = Number(match[1]);
    if (claimed === registry.count) continue;
    claims.push({
      file,
      line: lineAt(source, match.index ?? 0),
      message:
        `a Stats cell counts ${claimed} Blocks in the registry, but the catalog holds ` +
        `${registry.count}. Correct the value, or regenerate the catalog if a Block was added.`,
    });
  }
  return claims;
};

/** Every rule, over one file. */
export const checkClaims = (file: string, source: string, registry: Registry): Claim[] => [
  ...checkCount(file, source, registry),
  ...checkSample(file, source, registry),
  ...checkEnumeration(file, source, registry),
  ...checkStatCell(file, source, registry),
];

// --- CLI ---------------------------------------------------------------------

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");

const CATALOG = join(repoRoot, "artifacts", "web", "src", "lib", "blocks", "catalog.json");

/**
 * The prose an agent or an adopter reads to learn what exists.
 *
 * `.agents/skills/` only, never `.claude/skills/`: the latter is a generated
 * byte-identical mirror, so a claim corrected here is corrected there by
 * `pnpm harness`, and `harness:check` fails if it was not. Listing both would
 * report every finding twice.
 *
 * Content MDX is here too, and it is the reason rule 4 exists: a page can
 * count the registry just as wrongly as a doc can, and until now nothing read
 * it. Listed by glob rather than by name so a new page is covered the day it
 * is written instead of the day someone remembers this file.
 */
const CONTENT_GLOB = "artifacts/web/content/**/*.mdx";

const SOURCES = [
  "README.md",
  "AGENTS.md",
  ".agents/skills/compose-page/SKILL.md",
  ".agents/skills/design-a-block/SKILL.md",
  ".agents/skills/find-skills/SKILL.md",
  ".agents/skills/no-em-dash-copy/SKILL.md",
  ".agents/skills/sync-changes/SKILL.md",
  ".agents/skills/write-a-skill/SKILL.md",
];

const isMain = (): boolean => {
  const entry = process.argv[1];
  return typeof entry === "string" && entry.endsWith("claims-check.ts");
};

if (isMain()) {
  const registry = registryFrom(readFileSync(CATALOG, "utf8"));

  const files = [...SOURCES, ...globSync(CONTENT_GLOB, { cwd: repoRoot }).sort()];

  const claims = files.flatMap((file) =>
    checkClaims(file, readFileSync(join(repoRoot, file), "utf8"), registry),
  );

  if (claims.length === 0) {
    process.stdout.write(
      `Claims check: ${files.length} files agree with the registry (${registry.count} Blocks)\n`,
    );
    process.exit(0);
  }

  process.stderr.write(
    `Claims check: ${claims.length} stale claim(s) about the Block registry\n\n`,
  );
  for (const claim of claims) {
    process.stderr.write(`  ${claim.file}:${claim.line} ${claim.message}\n\n`);
  }
  process.stderr.write(
    `  These are the sentences an authoring agent reads before it picks a Block. ` +
      `A stale one costs a Block that already exists.\n`,
  );
  process.exit(1);
}
